import type { Metadata } from "next";
import "./globals.css";
import { AosInit } from "@/components/aos.init";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="bg-black w-screen h-auto flex flex-col items-center justify-center">
        {/* <div className="w-screen h-20 bg-slate-100">
          <h1>Inicio</h1>
        </div> */}
        {children}
        <AosInit />
        {/* <div className="w-screen h-20 bg-slate-100">FIM</div> */}
      </body>
    </html>
  );
}
